name: Actions 😎

on: [push]

jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: |
            Cat/Assets
            Cat/Packages
            Cat/ProjectSettings
          key: Library-${{ hashFiles('Cat/Assets/**', 'Cat/Packages/**', 'Cat/ProjectSettings/**') }}

      # Test
      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v4
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #     UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      #     UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      #   with:
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: Cat
          allowDirtyBuild: true

      # Upload to itch.io
      - name: Upload to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/WebGL/WebGL
          project: gongbaodd/ghostly-paws
          channel: html5
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      # Upload to itch.io
      - name: Upload to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/WebGL/WebGL
          project: buckb1ck/ghostly-paws
          channel: html5
          api-key: ${{ secrets.ITCHIO_API_KEY_MARTIN }}

      # Output
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

      # Send Notification
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '✅ The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'